#include "Ext.h"

const EXT_ConfigType EXT_ConfigrationsSet [EXT_NUMBER_OF_CONFIGERED_PINS] = {\
/* intId,    interruptStatus,       portId,          pinId,      setSensebit0,                      setSensebit1  */
//{EXT_INT0, 	EXT_INTERRUPT_DISABLE, 	EXT_INT0_PORT, EXT_INT0_PIN,	EXT_INT0_SENSE_FALLING_EDGE_ISC00, 	EXT_INT0_SENSE_FALLING_EDGE_ISC01},
{EXT_INT1, 	EXT_INTERRUPT_ENABLE,  	EXT_INT1_PORT, EXT_INT1_PIN, 	EXT_INT1_SENSE_LOW_LEVEL_ISC11, 	EXT_INT1_SENSE_LOW_LEVEL_ISC10},
//{EXT_INT2, 	EXT_INTERRUPT_DISABLE, 	EXT_INT2_PORT, EXT_INT2_PIN, 	EXT_INT2_SENSE_FALLING_EDGE_ISC2,  	EXT_INT2_SENSE_FALLING_EDGE_ISC2}
};
